### ISSUE TITLE
Reddit Gallery Posts Should Not Redirect

### ISSUE THREAD

**Issue by janjuafarooq** [tom-james-watson/old-reddit-redirect#38] opened 2020-07-24 03:09 UTC
Reddit added album capability recently which allows multiple photos.  These are being redirected.  Example:

reddit.com/gallery/abcd

redirects to

old.reddit.com/gallery/abcd

resulting in page not found.

**Comment by amstan** [comment] 2020-07-24 06:48
Fixed in PR #35 ?

**Comment by tom-james-watson** [comment] 2020-07-24 14:28
Yup this is a duplicate of https://github.com/tom-james-watson/old-reddit-redirect/issues/33 and should have been fixed in https://github.com/tom-james-watson/old-reddit-redirect/pull/34 which has been released as version 1.2.0

If not, let me know.

**Closed by tom-james-watson** 2020-07-24 14:28 UTC
