### ISSUE TITLE
Bad redirects on preview.redd.it or i.redd.it

### ISSUE THREAD

**Issue by NickTheHalfling** [tom-james-watson/old-reddit-redirect#86] opened 2023-08-08 13:27 UTC
Hi, idk what a github is but I wanted to file a bug report and hope this is the right place.
I hope someone else is having this issue because it will be very silly if they aren't. 
Whenever I try to open an image on reddit, whether through a gallery or if it is a standalone photo, it sends me to this particular comment in an 11 year old thread from /r/funny. 

The URL in question: https://old.reddit.com/r/funny/comments/media/nice_hat/?url=https%3A%2F%2Fpreview.redd.it%2Ffpmh0bz0xrgb1.jpg%3Fwidth%3D1080%26format%3Dpjpg%26auto%3Dwebp%26s%3Df9317b566782c4502923235198c52a6651529993

You can see that the image URL is there... It just insists on making me read this old comment? I don't know. It stops when I disable the plugin, but then I have to slog through new reddit and would rather have birds peck my eyeballs out. Help me if you can, if not I guess I'll cope

**Comment by atanvardo** [comment] 2023-08-08 13:42
I'm having the same problem, it started several days ago, redirecting to the same post from r/funny. It doesn't happen always, but randomly, for example [in this post](https://old.reddit.com/r/MapPorn/comments/15ld9xz/endings_of_places_in_poland/). According to [this](https://old.reddit.com/r/help/comments/15kwhgy/why_is_every_image_link_i_click_on_directing_me/), it happens only in Firefox.

**Comment by tom-james-watson** [comment] 2023-08-08 14:17
Umm that is very strange. When I load https://old.reddit.com/r/MapPorn/comments/15ld9xz/endings_of_places_in_poland/ and click on the image I get taken to https://i.redd.it/8u1yl4kmwugb1.jpg as expected.

I've never seen this. Honestly it sounds like it's most likely an issue on reddit's end.

What exactly are the reproduction steps? What are you clicking on? The expanded image at the top of the comments page?

Can you please right click the image and press "copy link" and paste it here? For the above link it should be https://i.redd.it/8u1yl4kmwugb1.jpg, for example.

**Comment by GoodwinJJ** [comment] 2023-08-08 14:46
If your are running Firefox Beta with old.reddit.redirect in a collection, check the version number in add-on manager. Mine was still on v1.6.1 and did not auto update to the latest release. 

To resolve the issue I had to:
[1] uninstall the add-on from Firefox Beta
[2] log into Firefox add-on website
[3] delete old.reddit.redirect from my collection
[4] re add old.reddit.redirect to my collection
[5] Wait for the add-on to be re-sync to Firefox Beta to update to v1.7.1.

Now reddit is working as expected.

**Comment by NickTheHalfling** [comment] 2023-08-08 14:54
> Can you please right click the image and press "copy link" and paste it here? For the above link it should be https://i.redd.it/8u1yl4kmwugb1.jpg, for example.

Here's the copied link location: https://preview.redd.it/8u1yl4kmwugb1.jpg?width=1024&auto=webp&s=2d9a56eda3ea4165620490085467f61e7adf5c85
It's definitely the url that leads to the image, but clicking on it sends me to the "nice hat" post as described in the reddit thread posted by atanvardo. I'm not on the beta version of firefox either. I'll try re-installing the extension and will report back if it works o7

**Comment by tom-james-watson** [comment] 2023-08-08 16:07
Hmm still not really sure what's going on because I can't recreate without the extension and with the extension (latest) I don't see it either.

Will close this out because it seems like as long as you have the latest version of the extension then it doesn't happen.

**Comment by tom-james-watson** [comment] 2023-08-08 18:41
A user reported this issue on Firefox store and attached a video: https://imgur.com/xP95XAE

It looks like maybe Reddit have changed the link format for images and that's causing a bad redirect on their end. I will investigate more when at a computer.

**Comment by Gragagoa** [comment] 2023-08-08 18:50
I registered to report the same issue. Nearly image links redirect to the same 'funny hat' post. Seems to be something that someone at reddit is doing on purpose.

**Comment by tom-james-watson** [comment] 2023-08-08 19:04
The weird redirect is happening on reddit's side (obviously). If you disable the extension completely and load

https://old.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2F8u1yl4kmwugb1.jpg%3Fwidth%3D1024%26auto%3Dwebp%26s%3D2d9a56eda3ea4165620490085467f61e7adf5c85

you will end up on

https://old.reddit.com/r/funny/comments/media/nice_hat/?url=https%3A%2F%2Fpreview.redd.it%2F8u1yl4kmwugb1.jpg%3Fwidth%3D1024%26auto%3Dwebp%26s%3D2d9a56eda3ea4165620490085467f61e7adf5c85

will investigate what leads to this `media?url=` path being loaded.

**Comment by tom-james-watson** [comment] 2023-08-08 19:22
OK I've worked it out.

_Sometimes_, when you request https://i.redd.it/8u1yl4kmwugb1.jpg, Reddit will return a redirect to https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2F8u1yl4kmwugb1.jpg.

The extension is redirecting this to https://old.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2F8u1yl4kmwugb1.jpg

https://old.reddit.com/media?url=anything redirects to "nice hat", for some strange reason.

I will make a new release that avoids redirecting `www.reddit.com/media...`, which will fix this problem.

**Closed** 2023-08-08 19:22 UTC

**Comment by tom-james-watson** [comment] 2023-08-08 19:25
Version 1.7.2 has been published to both chrome and firefox and should address this issue. It can take a few days for the new versions to get through approval.

**Comment by tom-james-watson** [comment] 2023-08-08 19:27
Thanks for bringing this to my attention, all!

**Comment by tom-james-watson** [comment] 2023-08-08 19:29
The last thing I would add is that the urls in the format https://i.redd.it/8u1yl4kmwugb1.jpg redirect to  https://www.reddit.com/media?url=... seems to be random, maybe A/B testing. Unfortunately with the URLs in the format of  https://www.reddit.com/media?url= we don't seem to be able to apply our existing workaround that ensures the raw image file loads. If this change is going to be rolled out on reddit's side for all image links then we will be back to loading images in the crappy HTML wrapper that Old Reddit does natively.

**Comment by Randomno** [comment] 2023-08-08 21:01
> https://old.reddit.com/media?url=anything redirects to "nice hat", for some strange reason.

Because the nice hat post happens to have the shortlink of "media", out of any random 5 letter sequence.

**Comment by tom-james-watson** [comment] 2023-08-08 21:48
Ahh right, of course!

**Comment by Scotty-Trees** [comment] 2023-08-08 22:11
I know this issue is closed so I'll try to be brief. I just came across this issue from a different issue unrelated to this. But (!) I just wanted to say, thank you so very much for not only making this add-on, but also actively maintaining support for it. Truly happy to witness your level of commitment. Always difficult to see when some add-ons haven't seen an update in years.

I used New Reddit almost exclusively since it was introduced (sorry I came from the Digg migration so new felt more familiar), but within the last year I (re)discovered Old Reddit and now prefer it. Thanks to your add-on (and Reddit Comment Collapser add-on) I can browse Reddit exactly the way I like to. I don't know how long any of this will last, but let me just say I am grateful for the time spent.

If I do come across any future bugs, I will let you know! Thanks again for this, cheers!

**Comment by Gragagoa** [comment] 2023-08-09 17:15
For some reason when I disable the add-on then re-enable it, it works again without redirecting to the wrong URL. Firefox. But every time I restart my browser the add-on begins redirecting images to the same incorrect URL.

**Comment by tom-james-watson** [comment] 2023-08-09 19:25
Unfortunately you just need to wait for 1.7.2 to reach the addon store.

**Comment by morops** [comment] 2023-08-11 02:23
This issue was mystifying me. But now that it is figured out:
1) thanks for the quick turn on a fix
2) this is one of the funnier "bugs" I have seen in my life, and the root cause analysis tickles my brain in the perfect way

**Comment by Gragagoa** [comment] 2023-08-12 17:06
Is anyone still having the same issues even with the updates? I find that I have to manually deactivate the reactive the add on every single time I restart Firefox. When I restart the browser it refuses to redirect images to a standalone page and remains in the main site with a bordered image and a login button.

**Comment by tom-james-watson** [comment] 2023-08-12 18:07
That's not that same issue, that's a result of Reddit serving the images via this new URL format and I don't think there's anything we can do - looks like it's out of our hands.

**Comment by jwdevel** [comment] 2023-08-22 18:44
Just FYI, this behavior is (currently) controlled by the `Accept:` header on the request.

A typical browser request might have: `Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8'

and that gets the redirect response.

However, if you send a request with no text/html and such in the `Accept:` type, it will give you the image directly.

Eg:  `Accept: image/avif,image/webp,*/*;q=0.8`

So, if this extension has the ability to control the request headers, that would be one way to fix it.

Other extensions can do such things (eg: [simple-modify-headers](https://addons.mozilla.org/en-US/firefox/addon/simple-modify-header/)), so it should be possible.

**Comment by tom-james-watson** [comment] 2023-08-23 16:17
It's reddit itself that sometimes decides to redirect https://i.redd.it/8u1yl4kmwugb1.jpg to https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2F8u1yl4kmwugb1.jpg, so unfortunately no.

**Comment by kushagharahi** [comment] 2023-09-17 21:27
Oh man. This is probably an unhelpful comment, but I was getting redirected to that "nice hat" 11 year old r/funny post linked in the OP. It's taken me weeks to figure out that i.reddit links cause the redirect. 

After figuring that out, I found via [the following post](https://old.reddit.com/r/help/comments/15l5t16/old_reddit_redirects_to_a_weird_post/) that reinstalling this extension would fix it. Which it did (for now).
