### ISSUE TITLE
Gallery endpoints are not mapped for the old.reddit domain and result in a 404 response

### ISSUE THREAD

**Issue by catchcase** [tom-james-watson/old-reddit-redirect#36] opened 2020-07-20 09:47 UTC
I get a 404 when clicking images that bring me to a gallery page, e.g. reddit.com/gallery/hudpes
These are seemingly redirected but there is no equivalent endpoint for the old.reddit.com domain.

To Reproduce:
- Go to this page: https://old.reddit.com/r/boardgames/comments/hudpes/i_finally_completed_my_3d_printed_settlers_of/
- Confirm 404 response when clicking the image gallery link with the extension active
- Repeat the first step with the extension deactivated (e.g. private window); note that the endpoit exists for https://www.reddit.com/gallery/hudpes

I do not have a proposed fix besides excluding gallery pages from redirects

**Comment by tom-james-watson** [comment] 2020-07-20 09:55
Duplicate of https://github.com/tom-james-watson/old-reddit-redirect/issues/33.

A fix for this was pushed out as v1.2.0 yesterday.

**Closed by tom-james-watson** 2020-07-20 09:55 UTC
