### ISSUE TITLE
Image links redirecting to reddit post from 2011

### ISSUE THREAD

**Issue by Wateraga** [tom-james-watson/old-reddit-redirect#91] opened 2023-08-27 22:27 UTC
When I click an image link it redirects me to a reddit post from 2011

Found these 2 posts after some troubleshooting, are these related to this extension?

https://old.reddit.com/r/bugs/comments/15q94do/image_links_redirect_to_an_old_post_rather_than/

https://old.reddit.com/r/help/comments/15q20i0/image_links_redirect_to_an_old_post_rather_than/

Original link that prompted me to solve the problem:
https://old.reddit.com/r/funny/comments/media/nice_hat/?url=https%3A%2F%2Fpreview.redd.it%2Fn6d81pghypkb1.jpeg%3Fwidth%3D3840%26format%3Dpjpg%26auto%3Dwebp%26s%3Dbf572296738bdb33cb78fa80db7adcde3a70ae6f

I cut:
preview.redd.it%2Fn6d81pghypkb1.jpeg%3Fwidth%3D3840%26format%3Dpjpg%26auto%3Dwebp%26s%3Dbf572296738bdb33cb78fa80db7adcde3a70ae6f
from the link and tried to go to the page which gave just the 2 reddit posts about the issue as google results.

I did remove and reinstall the extension which solved the issue but thought I'd post here in case you weren't aware of the problem.

**Comment by tom-james-watson** [comment] 2023-08-28 06:33
Duplicate of https://github.com/tom-james-watson/old-reddit-redirect/issues/86

**Closed by tom-james-watson** 2023-08-28 06:33 UTC
