### ISSUE TITLE
Polls do not work with Old Reddit Redirect

### ISSUE THREAD

**Issue by Invisible40** [tom-james-watson/old-reddit-redirect#102] opened 2023-12-08 05:55 UTC
Is there a way to get polls to work with Old Reddit Redirect? When you open a post with a poll (with the extension enabled), it appears as a Chrome 404 page with "www.reddit.com refused to connect."

![image](https://github.com/tom-james-watson/old-reddit-redirect/assets/8390311/24c1766f-f941-44b1-8442-e4c3db4e79dd)

![image](https://github.com/tom-james-watson/old-reddit-redirect/assets/8390311/8a2a7baa-d767-4a8c-a7b2-d89f254303b2)

**Comment by tom-james-watson** [comment] 2023-12-11 07:34
Do you have an example URL?

**Comment by Invisible40** [comment] 2023-12-21 03:50
https://old.reddit.com/r/bostonceltics/comments/185z2v6/celtics_inseason_tournament_poll/ -> For here, the link just says "[View Poll](https://www.reddit.com/poll/185z2v6)". Click it, and you get the "reddit.com failed to connect" error above

https://old.reddit.com/r/bostonceltics/comments/13jmb3g/poll_would_you_pay_jaylen_brown_the_supermax/

**Comment by tom-james-watson** [comment] 2024-04-16 23:00
This should just take you to the poll on new reddit. I can't reproduce the bug, so I'm going to close this out. Looks like probably a connection issue on your end?

**Closed by tom-james-watson** 2024-04-16 23:00 UTC

**Comment by Nyunyun** [comment] 2024-07-07 21:29
Just adding context if someone else sees this, the expansion is a Reddit Enhancement Suite feature and that's getting blocked by either uBlock (or other content blockers) or your browsers tracking protection.

**Comment by KaKi87** [comment] 2025-12-05 20:26
Hi,

I don't have Reddit Enhancement Suite so I don't have that embed, but when I click "View Poll", nothing happens except what looks like a page refresh.

I'm guessing what really happens is a redirect to New Reddit that is reverted by Old Reddit Redirect, but when it's specifically for a poll, it would be nice to allowlist it, though maybe open it in a new tab by default, I guess.

Thanks
