### ISSUE TITLE
*.reddit.com subreddit URLs now redirecting to reddit home page and returning HTTPStatusCode 301 Permanently Moved

### ISSUE THREAD

**Issue by BlakeRunkle1** [tom-james-watson/old-reddit-redirect#142] opened 2024-10-03 14:29 UTC
When navigating to a URL formatted like "news.reddit.com" instead of redirecting to "old.reddit.com/r/news" the URL now redirects to the home page. These URLs are being marked as HTTPStatusCode 301 Permanently Moved. I've attempted to make various fixed in both the v2 and v3 versions but I'm unable to intercept the URL before it is rerouted.

**Comment by tom-james-watson** [comment] 2024-10-03 14:31
Hey. This is a duplicate of https://github.com/tom-james-watson/old-reddit-redirect/issues/140.

This isn't anything to do with the extension - this is a change in Reddit itself (https://old.reddit.com/r/help/comments/1fojw02/cleaning_up_some_lowusage_features/) and is not something that the extension ever had any functionality for specifically. I'd appreciate if you could update your review to reflect that, thanks! 🙏

**Comment by BlakeRunkle1** [comment] 2024-10-03 14:32
Appreciate the quick response, apologies for not noticing the duplicate.

**Closed by tom-james-watson** 2024-10-03 14:31 UTC

**Comment by lbeckman314** [comment] 2024-10-07 18:51
Ran into this issue and had good luck with adding the [Redirector](https://einaregilsson.com/redirector/) extension by [Einar Egilsson](https://einaregilsson.com/) to handle the new subdomain redirect behavior (with all other cases still handled by the Old Reddit Redirect).

<a href="https://einaregilsson.com/redirector/">
  <img title="Redirector Extension" src="https://github.com/user-attachments/assets/9215101a-6624-485d-b6ca-b54b9e940f06"/>
</a>

---

Adapted [original comment](https://old.reddit.com/r/help/comments/1fojw02/cleaning_up_some_lowusage_features/lqjjvrp/) (by reddit user @brysonsucks):

> For the subdomain redirect issue I found an extension for firefox and chrome called redirector that seems to solve the issue for me:
> - https://addons.mozilla.org/en-US/firefox/addon/redirector/
> - https://chromewebstore.google.com/detail/redirector/ocgpenflpmgnfapjedencafcfakcekcd?hl=en
> 
> Here are my settings:
> - **Example url:** https://*.reddit.com/
> - **Include pattern:** https://*.reddit.com/
> - **Redirect to:** https://old.reddit.com/r/$1
> - **Pattern Type:** Wildcard
> 
> This also works for Brave and I assume Opera.

---

Big fan of the Old Reddit Redirect and have been using it for a number of years — big thanks for all your work on it!

**Comment by lbeckman314** [comment] 2024-10-07 18:53
Ah, just noticed @livejamie had the same recommendation!
> https://github.com/tom-james-watson/old-reddit-redirect/issues/140#issuecomment-2395266067
