### ISSUE TITLE
Incorrect redirect for share links

### ISSUE THREAD

**Issue by george-dy** [tom-james-watson/old-reddit-redirect#87] opened 2023-08-10 21:41 UTC
Looks like Reddit might be using some sort of link-sharing shortener/tracker that currently doesn't get redirected properly.

Link in question:
https://reddit.com/r/comics/s/TjDGhcl22d

Where it should actually redirect to:
https://old.reddit.com/r/comics/comments/15iyszj/rcomics_impromptu_crossover_event_2023/

Where it is currently redirecting to:
https://old.reddit.com/r/comics/submit?url=https://TjDGhcl22d

**Comment by arjunsrinivasan1997** [comment] 2023-08-12 05:48
Having a similiar issue with an example below:

Link:
https://reddit.com/r/popculturechat/s/WtltmM9scy

Where it should go:
https://old.reddit.com/r/popculturechat/comments/15ov2qq/selena_gomez_francia_raisa_had_dinner_with/

Where it goes:
https://old.reddit.com/r/popculturechat/submit?url=https%3A%2F%2FWtltmM9scy

**Comment by arjunsrinivasan1997** [comment] 2023-08-12 05:55
A link like this is working fine though:https://old.reddit.com/r/AITAH/comments/15d2bzk/aita_for_suggesting_calling_off_the_wedding/

**Comment by Squirreljetpack** [comment] 2023-08-12 17:56
Images starting with https://www.reddit.com/media? , if extension is enabled get redirected to https://old.reddit.com/r/funny/comments/media/nice_hat/?url=https%3A%2F%2Fpreview.redd.it%2Fuhgbt8jiqnhb1.png%3Fwidth%3D973%26format%3Dpng%26auto%3Dwebp%26s%3D39cf7c5f923ac52651c441ed06d5e38e167643b4

suggest exclude https://www.reddit.com/media?

**Comment by tom-james-watson** [comment] 2023-08-12 18:08
@Squirreljetpack that is https://github.com/tom-james-watson/old-reddit-redirect/issues/86 and is already fixed in 1.7.2

**Comment by CruisnGrrl** [comment] 2023-08-13 04:45
Also having this issue of being prompted to submit a url when going to a shortened URL
https://www.reddit.com/r/CatastrophicFailure/s/WzVPNkSsxv takes me to https://old.reddit.com/r/CatastrophicFailure/submit?url=https%3A%2F%2FWzVPNkSsxv instead of https://old.reddit.com/r/CatastrophicFailure/comments/15pip2i/aug_12_2023_house_explosion_near_pittsburgh_pa/

**Comment by tom-james-watson** [comment] 2023-08-13 11:54
By the way, I assume the problem is when you are being sent these links, but I would discourage people from using these links as they are just a way for Reddit to implement deep tracking of users - you end up redirected to a page that has something like `share_id=iW_uuA86wfEdv_ypZ0cIV` in the URL. People should just copy the plain comments URL.

Working on a fix regardless though.

**Closed** 2023-08-13 11:59 UTC

**Comment by tom-james-watson** [comment] 2023-08-13 12:04
I've published version 1.7.3 which fixes this - it should make it out to Firefox/Chrome over the next few days.

**Comment by tom-james-watson** [comment] 2023-08-16 09:18
This is now approved and released on both Chrome and Firefox.

**Comment by arjunsrinivasan1997** [comment] 2023-08-17 22:18
Thanks for the fix!

**Comment by elmo667** [comment] 2023-10-01 11:56
Could you kindly have another check on this? Because the latest version thats available for firefox is 1.7.0 still @tom-james-watson
