### ISSUE TITLE
Doesn't work consistently with gallery links.

### ISSUE THREAD

**Issue by Rtizer-9** [tom-james-watson/old-reddit-redirect#55] opened 2021-08-15 07:38 UTC
I don't know what's been happening and I also understand it'll be little bit difficult to replicate but the extension doesn't work consistently on both Firefox Nightly and Brave for reddit gallery links. I waited for sometime and then it started working and then again not.

I also tried reloading (apart from clicking) the gallery links expecting it to convert but no it doesn't.

**Comment by Tattoo** [comment] 2021-11-17 08:12
It seems that gallery links are redirected incorrectly in Reddit. For example, https://www.reddit.com/gallery/qvbf7c becomes https://old.reddit.com/r/comicbooks/comments/qvbf7c/not_again_incredible_hulk_610/

**Comment by Rtizer-9** [comment] 2021-11-17 08:14
Oh, I wasn't aware of that.

**Comment by Tattoo** [comment] 2021-11-17 08:23
@Rtizer-9 ,

I'm just adding more information to your issue. I also wish this would be fixed :)

**Comment by tom-james-watson** [comment] 2021-11-17 08:46
This was fixed in https://github.com/tom-james-watson/old-reddit-redirect/issues/60/https://github.com/tom-james-watson/old-reddit-redirect/commit/7e41360e60c22c09ae9c366e60d3ef3a607804d3. I forgot there was this older issue which should have been merged with the new one!

> It seems that gallery links are redirected incorrectly in Reddit. For example, https://www.reddit.com/gallery/qvbf7c becomes https://old.reddit.com/r/comicbooks/comments/qvbf7c/not_again_incredible_hulk_610/

That is the correct and intended functionality.

**Closed by tom-james-watson** 2021-11-17 08:46 UTC

**Comment by Tattoo** [comment] 2021-11-17 13:34
I would like to implore you to reconsider that this is intended functionality. Currently, one cannot ever see galleries

**Comment by tom-james-watson** [comment] 2021-11-17 15:31
That post you linked above would be listed as a link to https://new.reddit.com/r/comicbooks/comments/qvbf7c/not_again_incredible_hulk_610. On old reddit, reddit are linking you to https://www.reddit.com/gallery/qvbf7c instead, but that is pointless because you a) can't see the comments, b) get the new reddit ui and c) you can see all of the images on the old reddit comment page anyway. I assume you would prefer the gallery page, but I think you're in the minority there.

**Comment by tom-james-watson** [comment] 2021-11-17 15:32
Maybe you're not aware that you can see the gallery on the old reddit comment page?

https://user-images.githubusercontent.com/3852719/142230611-f4a97ce3-b9f9-40af-9bef-cddf257f5108.mp4

**Comment by Tattoo** [comment] 2021-11-18 11:06
Weird, for me it looks like this:

![Screenshot 2021-11-18 at 13 05 17](https://user-images.githubusercontent.com/280218/142403983-9427cadc-a460-44d0-9891-66b2e0f4376b.png)

ie. no Gallery

**Comment by Tattoo** [comment] 2021-11-18 11:08
Oh it's because I have `compress the link display` setting in Reddit settings on. Nevermind, yes the plugin works as intended.
