### ISSUE TITLE
Can we get a quick toggle for the toolbar button so that I can turn Old Reddit Redirect on and off?

### ISSUE THREAD

**Issue by mrbigmouth502** [tom-james-watson/old-reddit-redirect#123] opened 2024-05-16 06:33 UTC
Sometimes I need to switch to New Reddit in order to access certain features, like reading the rules on some subreddits, reading selftext on certain gallery posts (since Reddit Enhancement Suite doesn't support gallery posts that have selftext below the image), and for reading user bios.

At the moment I'm not actually using Old Reddit Redirect, but I have my account set to make Old Reddit the default view. Rumor has it that Reddit is planning on getting rid of this feature. https://np.reddit.com/r/Enhancement/comments/1css8cy/the_preference_to_have_old_reddit_as_the_default/

Right now, I'm using a bookmarklet that switches from `www.reddit.com` to `new.reddit.com` for the current page. I'm using this because Old Reddit Redirect doesn't have an option to quickly turn on and off. This bookmarklet relies on Reddit allowing you to set Old Reddit as the default for your account.

If it matters, I'm using Firefox on EndeavourOS, which is a distro based on Arch Linux. I'm sure this feature would work just fine on Chromium-based browsers though.

**Comment by tom-james-watson** [comment] 2024-05-16 06:42
Duplicate of https://github.com/tom-james-watson/old-reddit-redirect/issues/68

**Closed by tom-james-watson** 2024-05-16 06:42 UTC
