### ISSUE TITLE
Redirection partially broken now

### ISSUE THREAD

**Issue by HereticBG** [tom-james-watson/old-reddit-redirect#141] opened 2024-10-03 03:14 UTC
Before it worked perfectly and going to (subreddit).reddit.com redirected to old.reddit.com/r/(subreddit) but now doing (subreddit).reddit.com takes you to the old.reddit.com homepage instead

**Comment by tom-james-watson** [comment] 2024-10-03 07:56
Hey. This isa duplicate of https://github.com/tom-james-watson/old-reddit-redirect/issues/140.

This isn't anything to do with the extension - this is a change in Reddit itself and is not something that the extension ever had any functionality for specifically. I'd appreciate if you could update your review to reflect that, thanks! 🙏

**Closed by tom-james-watson** 2024-10-03 07:56 UTC
